### ISSUE TITLE
Issues dislaying the "Released year of the manga"

### ISSUE THREAD

**Issue by HassanNdam** [HassanNdam/Application-manga#1]
It's not possible for now to display the year of the releasing of the manga. The bug is being resolved..

**Comment by andrewbaisden** [comment]
@HassanNdam did you resolve it? What is the problem with the release year display? I tried the code on your repo and it worked. The release year filter will only filter by dates if they are present in the Anime Data List. I did not code any error handling for it so if you try to filter by a date that does not exist then it just won't show anything.

**Comment by HassanNdam** [comment]
Hello @andrewbaisden All is ok now and you were right. I didn't understand that like that. Thank you so much
